export const data = {
  products: [
    {
      id: 'RX-001',
      name: 'RX.Torax (PA)',
      image: '',
      price: 120,
      countInStock: 10,
      category: '',
      numReviews: 10,
      description: 'Radiografía de Torax',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "Traumatología",
      especialidadDetalle: "Traumatología",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "Traumatólogo",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: 'RX-006',
      name: 'RX. Antebrazo AP-L',
      image: '',
      price: 250,
      countInStock: 10,
      category: '',
      numReviews: 10,
      description: 'Radiografía de antebrazo',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: 'RX-007',
      name: 'RX.RAYOS X PORTATIL EN PISO',
      image: '',
      price: 150,
      countInStock: 15,
      category: '',
      numReviews: 14,
      description: 'Rayos x portatil de piso',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: 'RX-008',
      name: 'RX TORAX COVID',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category2',
      numReviews: 10,
      description: 'Rayos X Torax COVID',
      codigoProductoSin: 99100,
      unidadMedida: 58,
      especialidad: "Traumatología",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
    {
      id: 'RX-009',
      name: 'RX. TORAX PORTATIL UTI COVID',
      image: '',
      price: 65,
      countInStock: 5,
      category: 'Category3',
      numReviews: 10,
      description: 'Rayos X portatil UTI COVID',
      codigoProductoSin: 99100,
      descripcion: "ñÑáÁ",
      unidadMedida: 58,
      especialidad: "Traumatología",
      especialidadDetalle: "string",
      nroQuirofanoSalaOperaciones: 1,
      especialidadMedico: "string",
      nombreApellidoMedico: "Medicmel",
      nitDocumentoMedico: 392010028,
      nroMatriculaMedico: "string",
      nroFacturaMedico: 1,
    },
  ],
}
